/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// Placeholder types - will be replaced by generated types from API schema
export interface paths {
  "/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              token: string;
              user: any;
            };
          };
        };
      };
    };
  };
  "/media": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": any[];
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "multipart/form-data": {
            file: File;
            metadata?: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": any;
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    MediaItem: {
      id: string;
      filename: string;
      type: "image" | "video" | "audio";
      size: number;
      uploadedAt: string;
      url?: string;
      thumbnailUrl?: string;
      metadata?: Record<string, any>;
    };
    Gallery: {
      id: string;
      prompt: string;
      mediaItems: components["schemas"]["MediaItem"][];
      createdAt: string;
      status: "processing" | "completed" | "failed";
    };
    Story: {
      id: string;
      fileId: string;
      caption: string;
      content: string;
      createdAt: string;
      status: "processing" | "completed" | "failed";
    };
  };
} 