// Desktop Application Download Handler
// Generated by create_desktop_installer.py

export const DESKTOP_APP_CONFIG = {
  version: "1.0.0",
  downloads: {
    windows: "CrowsEye_Marketing_Suite_1.0.0_Windows.zip",
    macos: "CrowsEye_Marketing_Suite_1.0.0_macOS.zip",
    linux: "CrowsEye_Marketing_Suite_1.0.0_Linux.zip",
    source: "CrowsEye_Marketing_Suite_1.0.0_Source.zip"
  },
  baseUrl: "/downloads/desktop/"
};

export function downloadDesktopApp(platform) {
  const config = DESKTOP_APP_CONFIG;
  const filename = config.downloads[platform.toLowerCase()];
  
  if (!filename) {
    alert(`Download not available for ${platform}`);
    return;
  }
  
  // Create download link
  const link = document.createElement('a');
  link.href = config.baseUrl + filename;
  link.download = filename;
  link.style.display = 'none';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  
  // Track download
  console.log(`Desktop app download initiated: ${platform} - ${filename}`);
}

// Super user functionality removed - handled manually now 