import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms and Conditions - Crow\'s Eye',
  description: 'Terms and Conditions for using Crow\'s Eye services.',
};

const TermsAndConditionsPage = () => {
  return (
    <div className="min-h-screen bg-gray-900 text-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl sm:text-4xl font-bold text-center mb-2 bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">
            Terms and Conditions
          </h1>
          <p className="text-center text-gray-400 mb-8">Last Updated: July 7, 2025</p>

          <div className="bg-gray-800/50 p-6 sm:p-8 rounded-lg shadow-lg prose prose-invert prose-lg max-w-none">
            <p className="text-gray-400">
              Welcome to Crow's Eye. These Terms and Conditions ("Terms") govern your use of our website and services (collectively, the "Services"). By accessing or using our Services, you agree to be bound by these Terms. This document is intended to be a clear and transparent explanation of our terms; for full legal compliance, we recommend consulting with a legal professional.
            </p>

            <h2>1. User Accounts</h2>
            <p>
              To use most features of our Services, you must register for an account. You must be at least 13 years old to create an account. You agree to provide accurate and complete information during registration and to keep this information up to date. You are responsible for safeguarding your password and for all activities that occur under your account.
            </p>

            <h2>2. Subscriptions and Payments</h2>
            <p>
              Our Services are offered under various subscription plans ("Plans"). By selecting a paid Plan, you agree to pay the fees associated with that Plan.
            </p>
            <ul>
                <li><strong>Billing:</strong> All payments are processed through our third-party payment processor, Stripe. You agree to provide them with valid and updated payment information.</li>
                <li><strong>Automatic Renewal:</strong> Your subscription will automatically renew at the end of each billing cycle (e.g., monthly or yearly) unless you cancel it through your account settings before the end of the current period.</li>
                <li><strong>Cancellations:</strong> You may cancel your subscription at any time. The cancellation will take effect at the end of the current billing period, and you will not be charged for the next cycle. We do not offer refunds for partial subscription periods.</li>
            </ul>

            <h2>3. User-Generated Content</h2>
            <p>
              You are solely responsible for all content you create, upload, or post using our Services, including text, images, and videos ("Content"). You represent and warrant that you own or have the necessary licenses, rights, and permissions to your Content.
            </p>
            <p>
              You retain all ownership rights to your Content. However, by using the Services, you grant Crow's Eye a limited, worldwide, non-exclusive, royalty-free license to use, reproduce, store, and display your Content solely for the purpose of operating, providing, and improving the Services.
            </p>

            <h2>4. Use of AI Services</h2>
            <p>
              Our Services may include features that use artificial intelligence, such as Google Gemini, to help you generate Content. You understand and agree to the following:
            </p>
            <ul>
                <li>AI-generated content is probabilistic and may not always be accurate, unique, or free from errors.</li>
                <li>You are solely responsible for reviewing, editing, and verifying any Content generated by AI before you publish or use it.</li>
                <li>You must ensure your use of AI-generated content complies with all applicable laws and does not infringe on the rights of any third party.</li>
                <li>We are not liable for any damages or losses arising from your use of our AI features.</li>
            </ul>

            <h2>5. Acceptable Use Policy</h2>
            <p>You agree not to use the Services to:</p>
            <ul>
              <li>Upload or share any Content that is unlawful, harmful, defamatory, obscene, or infringing on intellectual property rights.</li>
              <li>Engage in any activity that interferes with or disrupts the Services, our servers, or networks.</li>
              <li>Attempt to gain unauthorized access to any part of the Services or to other users' accounts.</li>
              <li>Use any automated system ("bots", "spiders") to access the Services in a way that sends more requests to our servers than a human can reasonably produce in the same period.</li>
              <li>Reverse engineer, decompile, or otherwise attempt to discover the source code of the Services.</li>
            </ul>

            <h2>6. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Services immediately, without prior notice or liability, if you breach these Terms. Upon termination, your right to use the Services will cease immediately.
            </p>

            <h2>7. Disclaimer of Warranties and Limitation of Liability</h2>
            <p>
              The Services are provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranties, express or implied, that the Services will be uninterrupted, error-free, or secure. To the fullest extent permitted by law, Crow's Eye shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with your use of the Services.
            </p>
            
            <h2>8. Governing Law</h2>
            <p>
              These Terms shall be governed and construed in accordance with the laws of the State of Texas, United States, without regard to its conflict of law provisions.
            </p>

            <h2>9. Changes to These Terms</h2>
            <p>
              We reserve the right to modify or replace these Terms at any time. If a revision is material, we will make reasonable efforts to provide at least 30 days' notice prior to any new terms taking effect.
            </p>

            <h2>10. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at: support@crowseye.tech
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;